name: CI

on: [push, pull_request]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run Django migrations
        run: docker-compose run --rm django python django_order_app/manage.py migrate
        env:
          DATABASE_URL: postgres://user:password@db:5432/trading_db
        working-directory: .

      - name: Run Django tests
        run: docker-compose run --rm django pytest django_order_app/tests
        env:
          DATABASE_URL: postgres://user:password@db:5432/trading_db
        working-directory: .

      - name: Run FastAPI tests
        run: docker-compose run --rm fastapi pytest backend/fastapi_pricing_service/tests
        env:
          DATABASE_URL: postgres://user:password@db:5432/trading_db
        working-directory: .

      - name: Run Mutation Test
        run: pytest --mutation backend
        working-directory: backend

  frontend-test:
    runs-on: ubuntu-latest
    needs: backend-test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Node.js dependencies
        run: cd frontend-react && npm ci
      - name: Run Frontend Lint
        run: cd frontend-react && npm run lint
      - name: Run Frontend Tests
        run: cd frontend-react && npm test
      - name: Check Commit Message
        # This step assumes commitlint.config.js is at the root or correctly configured to be found.
        # It's better to install commitlint globally in the runner or locally in frontend-react.
        # For simplicity, if commitlint.config.js is at project root, this will work.
        run: npx commitlint --from=${{ github.event.pull_request.base.sha || github.sha }} --to=${{ github.sha }}
        # No working-directory here if commitlint.config.js is at root, otherwise specify.

  flutter-test:
    runs-on: ubuntu-latest
    needs: backend-test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
      - name: Install Flutter dependencies
        run: cd flutter-app && flutter pub get
      - name: Run Flutter Tests
        run: cd flutter-app && flutter test
      - name: Run Flutter Analyze
        run: cd flutter-app && flutter analyze # Add Flutter linting
